export const projects = [
  {
    slug: "dubai-logistics-platform",
    title: { en: "Dubai Logistics Platform", ar: "منصة لوجستية في دبي" },
    description: {
      en: "Fleet and logistics management platform for large transport companies.",
      ar: "منصة لإدارة الأسطول والخدمات اللوجستية لشركات النقل.",
    },
    image: "https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=80",
    category: "Logistics",
    client: "Dubai Transport Group",
    country: "UAE",
    problem: { en: "Transport companies struggled to track fleet operations.", ar: "الشركات كانت تواجه صعوبة في متابعة الأسطول." },
    solution: { en: "We built a real-time tracking logistics platform.", ar: "قمنا ببناء منصة تتبع لحظي للأسطول." },
    tech: ["Next.js", "Node.js", "PostgreSQL", "AWS"],
    results: ["45% faster operations", "Real-time fleet tracking", "30% cost reduction"],
  },
  {
    slug: "saudi-fintech-dashboard",
    title: { en: "Saudi Fintech Dashboard", ar: "لوحة تحكم فينتك سعودية" },
    description: { en: "Advanced analytics dashboard for fintech startups.", ar: "لوحة تحكم تحليلية لشركات الفينتك." },
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
    category: "Fintech",
    client: "Riyadh Finance",
    country: "Saudi Arabia",
    problem: { en: "Financial data was fragmented across systems.", ar: "البيانات المالية كانت موزعة عبر عدة أنظمة." },
    solution: { en: "Unified fintech dashboard with real-time insights.", ar: "لوحة تحكم موحدة مع تحليلات لحظية." },
    tech: ["Next.js", "Python", "FastAPI", "Redis"],
    results: ["70% faster reporting", "Real-time analytics", "Centralized financial data"],
  },
  {
    slug: "egypt-real-estate-portal",
    title: { en: "Egypt Real Estate Portal", ar: "بوابة عقارات مصر" },
    description: { en: "Property marketplace for buying and renting homes.", ar: "منصة لبيع وتأجير العقارات." },
    image: "https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800&q=80",
    category: "Real Estate",
    client: "Cairo Properties",
    country: "Egypt",
    problem: { en: "Real estate listings were scattered across multiple websites.", ar: "الإعلانات العقارية كانت متفرقة." },
    solution: { en: "Unified portal for property listings and agents.", ar: "بوابة موحدة للعقارات والوكلاء." },
    tech: ["Next.js", "MongoDB", "Stripe"],
    results: ["200k users", "5000+ listings", "Top 3 real estate portals"],
  },
  {
    slug: "dubai-mobile-banking",
    title: { en: "Dubai Mobile Banking App", ar: "تطبيق بنكي في دبي" },
    description: { en: "Secure mobile banking application.", ar: "تطبيق بنكي آمن." },
    image: "https://images.unsplash.com/photo-1601597111158-2fceff292cdc?w=800&q=80",
    category: "Banking",
    client: "Emirates Bank",
    country: "UAE",
    problem: { en: "Customers needed better mobile banking experience.", ar: "المستخدمون احتاجوا تجربة مصرفية أفضل." },
    solution: { en: "Modern mobile banking platform.", ar: "منصة مصرفية حديثة." },
    tech: ["React Native", "Node.js", "AWS"],
    results: ["1M downloads", "Secure transactions", "4.8 app rating"],
  },
  {
    slug: "saudi-government-portal",
    title: { en: "Saudi Government Portal", ar: "بوابة الحكومة السعودية" },
    description: { en: "Digital services portal for citizens.", ar: "بوابة خدمات حكومية رقمية." },
    image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=800&q=80",
    category: "Government",
    client: "Saudi Digital Authority",
    country: "Saudi Arabia",
    problem: { en: "Citizens needed online government services.", ar: "الحاجة لخدمات حكومية رقمية." },
    solution: { en: "Unified digital government portal.", ar: "بوابة حكومية موحدة." },
    tech: ["Next.js", "Java", "Oracle"],
    results: ["5M users", "100+ services", "National rollout"],
  },
  {
    slug: "uae-aviation-analytics",
    title: { en: "UAE Aviation Analytics", ar: "تحليلات الطيران الإماراتية" },
    description: { en: "Airline performance analytics platform.", ar: "منصة تحليلات شركات الطيران." },
    image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?w=800&q=80",
    category: "Aviation",
    client: "Emirates Aviation",
    country: "UAE",
    problem: { en: "Airlines needed performance analytics.", ar: "شركات الطيران احتاجت تحليلات الأداء." },
    solution: { en: "Data analytics platform for aviation.", ar: "منصة تحليل بيانات الطيران." },
    tech: ["Next.js", "Python", "BigQuery"],
    results: ["Real-time flight analytics", "Operational insights", "Cost optimization"],
  },
  {
    slug: "qatar-healthcare-system",
    title: { en: "Qatar Healthcare Management", ar: "نظام إدارة الرعاية الصحية في قطر" },
    description: { en: "Integrated hospital management system for leading hospitals.", ar: "نظام متكامل لإدارة المستشفيات." },
    image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&q=80",
    category: "Healthcare",
    client: "Hamad Medical Corporation",
    country: "Qatar",
    problem: { en: "Hospitals managed patient data manually.", ar: "المستشفيات كانت تدير بيانات المرضى يدوياً." },
    solution: { en: "Fully digital patient and hospital management system.", ar: "نظام رقمي متكامل لإدارة المرضى والمستشفيات." },
    tech: ["React", "Node.js", "PostgreSQL", "Docker"],
    results: ["60% faster patient intake", "Zero paper records", "95% staff satisfaction"],
  },
  {
    slug: "egypt-elearning-platform",
    title: { en: "Egypt E-Learning Platform", ar: "منصة التعلم الإلكتروني في مصر" },
    description: { en: "Online education platform for K-12 students.", ar: "منصة تعليمية إلكترونية لطلاب المدارس." },
    image: "https://images.unsplash.com/photo-1501504905252-473c47e087f8?w=800&q=80",
    category: "Education",
    client: "Ministry of Education Egypt",
    country: "Egypt",
    problem: { en: "Students lacked access to quality digital learning tools.", ar: "الطلاب يفتقرون لأدوات تعليم رقمي جيدة." },
    solution: { en: "Interactive e-learning platform with live classes and assessments.", ar: "منصة تعليمية تفاعلية بفصول مباشرة واختبارات." },
    tech: ["Next.js", "WebRTC", "MongoDB", "AWS"],
    results: ["2M students onboarded", "10k+ lessons", "80% engagement rate"],
  },
  {
    slug: "kuwait-hr-management",
    title: { en: "Kuwait HR Management Suite", ar: "نظام إدارة الموارد البشرية في الكويت" },
    description: { en: "Complete HR and payroll management system.", ar: "نظام متكامل لإدارة الموارد البشرية والرواتب." },
    image: "https://images.unsplash.com/photo-1542744094-3a31f272c490?w=800&q=80",
    category: "HR",
    client: "Kuwait National Industries",
    country: "Kuwait",
    problem: { en: "HR processes were slow and paper-based.", ar: "إجراءات الموارد البشرية كانت بطيئة وورقية." },
    solution: { en: "End-to-end digital HR and payroll automation.", ar: "أتمتة كاملة لعمليات الموارد البشرية والرواتب." },
    tech: ["Vue.js", "Laravel", "MySQL", "Redis"],
    results: ["50% HR cost reduction", "Automated payroll", "Real-time reporting"],
  },
  {
    slug: "uae-retail-pos",
    title: { en: "UAE Smart Retail POS", ar: "نظام نقاط البيع الذكي في الإمارات" },
    description: { en: "Cloud-based point-of-sale system for retail chains.", ar: "نظام نقاط بيع سحابي لسلاسل التجزئة." },
    image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=800&q=80",
    category: "Retail",
    client: "Al Futtaim Retail",
    country: "UAE",
    problem: { en: "Retail stores used outdated legacy POS systems.", ar: "محلات التجزئة كانت تستخدم أنظمة قديمة." },
    solution: { en: "Modern cloud POS with inventory and analytics.", ar: "نظام نقاط بيع حديث مع إدارة مخزون وتحليلات." },
    tech: ["React", "Node.js", "PostgreSQL", "Stripe"],
    results: ["300+ stores connected", "Real-time inventory", "25% sales increase"],
  },
  {
    slug: "saudi-supply-chain",
    title: { en: "Saudi Supply Chain Platform", ar: "منصة سلسلة التوريد السعودية" },
    description: { en: "End-to-end supply chain visibility platform.", ar: "منصة لرؤية سلسلة التوريد من البداية للنهاية." },
    image: "https://images.unsplash.com/photo-1553413077-190dd305871c?w=800&q=80",
    category: "Logistics",
    client: "SABIC Logistics",
    country: "Saudi Arabia",
    problem: { en: "Supply chain had no real-time visibility.", ar: "سلسلة التوريد كانت تفتقر للرؤية اللحظية." },
    solution: { en: "Real-time supply chain tracking and analytics.", ar: "تتبع وتحليلات لحظية لسلسلة التوريد." },
    tech: ["Next.js", "Kafka", "PostgreSQL", "AWS"],
    results: ["40% faster delivery", "Full supply visibility", "15% cost savings"],
  },
  {
    slug: "egypt-payment-gateway",
    title: { en: "Egypt Payment Gateway", ar: "بوابة دفع إلكتروني مصرية" },
    description: { en: "Secure payment processing gateway for Egyptian businesses.", ar: "بوابة دفع آمنة للشركات المصرية." },
    image: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&q=80",
    category: "Fintech",
    client: "Fawry Digital",
    country: "Egypt",
    problem: { en: "Local businesses lacked secure digital payment options.", ar: "الشركات المحلية افتقرت لخيارات دفع رقمي آمنة." },
    solution: { en: "Multi-channel payment gateway with fraud protection.", ar: "بوابة دفع متعددة القنوات مع حماية من الاحتيال." },
    tech: ["Node.js", "PostgreSQL", "Redis", "Stripe API"],
    results: ["500k+ transactions/day", "99.9% uptime", "0.01% fraud rate"],
  },
  {
    slug: "qatar-smart-city",
    title: { en: "Qatar Smart City Dashboard", ar: "لوحة تحكم المدينة الذكية في قطر" },
    description: { en: "Unified smart city monitoring and control platform.", ar: "منصة موحدة لمراقبة وتحكم المدينة الذكية." },
    image: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=800&q=80",
    category: "Government",
    client: "Qatar Smart Infrastructure",
    country: "Qatar",
    problem: { en: "City services were managed in disconnected silos.", ar: "خدمات المدينة كانت تُدار بشكل منفصل." },
    solution: { en: "Integrated smart city platform connecting all city services.", ar: "منصة مدينة ذكية متكاملة تربط جميع الخدمات." },
    tech: ["Next.js", "IoT", "BigQuery", "GCP"],
    results: ["30% energy savings", "Unified city ops", "Real-time monitoring"],
  },
  {
    slug: "kuwait-insurance-platform",
    title: { en: "Kuwait Insurance Platform", ar: "منصة التأمين الكويتية" },
    description: { en: "Digital insurance management and claims platform.", ar: "منصة رقمية لإدارة التأمين والمطالبات." },
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?w=800&q=80",
    category: "Fintech",
    client: "Gulf Insurance Group",
    country: "Kuwait",
    problem: { en: "Insurance claims took weeks to process manually.", ar: "مطالبات التأمين كانت تستغرق أسابيع يدوياً." },
    solution: { en: "Automated digital insurance claims and management portal.", ar: "بوابة رقمية آلية لإدارة مطالبات التأمين." },
    tech: ["React", "Python", "FastAPI", "PostgreSQL"],
    results: ["Claims in 24 hours", "80% manual work reduced", "Customer satisfaction +40%"],
  },
  {
    slug: "uae-tourism-app",
    title: { en: "UAE Tourism Experience App", ar: "تطبيق السياحة الإماراتية" },
    description: { en: "AI-powered tourism guide and booking app for the UAE.", ar: "تطبيق سياحي ذكي مع حجز للإمارات." },
    image: "https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800&q=80",
    category: "Tourism",
    client: "Dubai Tourism Authority",
    country: "UAE",
    problem: { en: "Tourists struggled to discover and book local experiences.", ar: "السياح كانوا يجدون صعوبة في اكتشاف وحجز التجارب." },
    solution: { en: "AI-driven tourism app with personalized recommendations.", ar: "تطبيق سياحي بالذكاء الاصطناعي مع توصيات شخصية." },
    tech: ["Flutter", "Firebase", "Python", "OpenAI"],
    results: ["500k downloads", "4.9 app rating", "200+ experiences listed"],
  },
  {
    slug: "saudi-ecommerce-platform",
    title: { en: "Saudi E-Commerce Marketplace", ar: "منصة تجارة إلكترونية سعودية" },
    description: { en: "Multi-vendor e-commerce marketplace for Saudi consumers.", ar: "منصة تجارة إلكترونية متعددة البائعين للمستهلك السعودي." },
    image: "https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&q=80",
    category: "E-Commerce",
    client: "Noon Commerce",
    country: "Saudi Arabia",
    problem: { en: "Local vendors lacked a centralized sales platform.", ar: "البائعون المحليون افتقروا لمنصة بيع مركزية." },
    solution: { en: "Full-featured marketplace with vendor dashboards.", ar: "منصة متكاملة مع لوحات تحكم للبائعين." },
    tech: ["Next.js", "Node.js", "MongoDB", "Stripe"],
    results: ["10k vendors", "1M+ products", "3x sales growth"],
  },
  {
    slug: "egypt-telemedicine-app",
    title: { en: "Egypt Telemedicine Platform", ar: "منصة الطب عن بُعد في مصر" },
    description: { en: "Online doctor consultation and prescription platform.", ar: "منصة استشارات طبية إلكترونية ووصف أدوية." },
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800&q=80",
    category: "Healthcare",
    client: "Vezeeta Health",
    country: "Egypt",
    problem: { en: "Patients waited weeks for doctor appointments.", ar: "المرضى كانوا ينتظرون أسابيع للحصول على مواعيد." },
    solution: { en: "On-demand telemedicine app connecting patients with doctors.", ar: "تطبيق طب عن بُعد يربط المرضى بالأطباء فوراً." },
    tech: ["React Native", "WebRTC", "Node.js", "AWS"],
    results: ["300k consultations", "Avg wait: 5 minutes", "95% patient satisfaction"],
  },
  {
    slug: "qatar-aviation-operations",
    title: { en: "Qatar Airways Operations Hub", ar: "مركز عمليات الخطوط القطرية" },
    description: { en: "Operational control platform for airline ground services.", ar: "منصة تحكم تشغيلية لخدمات الأرض بالطيران." },
    image: "https://images.unsplash.com/photo-1464037866556-6812c9d1c72e?w=800&q=80",
    category: "Aviation",
    client: "Qatar Airways",
    country: "Qatar",
    problem: { en: "Ground operations were managed with legacy systems.", ar: "عمليات الأرض كانت تُدار بأنظمة قديمة." },
    solution: { en: "Real-time operations hub for ground crew coordination.", ar: "مركز عمليات لحظي لتنسيق طاقم الأرض." },
    tech: ["React", "Node.js", "WebSocket", "PostgreSQL"],
    results: ["35% faster turnaround", "Reduced delays", "Full ops visibility"],
  },
  {
    slug: "uae-property-management",
    title: { en: "UAE Property Management System", ar: "نظام إدارة العقارات الإماراتي" },
    description: { en: "End-to-end property rental and management platform.", ar: "منصة متكاملة لإدارة وتأجير العقارات." },
    image: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80",
    category: "Real Estate",
    client: "Emaar Properties",
    country: "UAE",
    problem: { en: "Property managers used spreadsheets for tenant management.", ar: "مديرو العقارات كانوا يستخدمون جداول بيانات." },
    solution: { en: "Digital property and tenant lifecycle management platform.", ar: "منصة رقمية لإدارة العقارات ودورة حياة المستأجرين." },
    tech: ["Next.js", "Laravel", "MySQL", "AWS S3"],
    results: ["5000+ units managed", "90% less admin work", "Online rent collection"],
  },
  {
    slug: "saudi-logistics-warehousing",
    title: { en: "Saudi Warehouse Management", ar: "نظام إدارة المستودعات السعودي" },
    description: { en: "Smart warehouse management system with IoT integration.", ar: "نظام إدارة مستودعات ذكي مع تكامل إنترنت الأشياء." },
    image: "https://images.unsplash.com/photo-1579847188949-b9a4de39d37f?w=800&q=80",
    category: "Logistics",
    client: "Aramex Saudi",
    country: "Saudi Arabia",
    problem: { en: "Warehouse inventory was tracked manually.", ar: "مخزون المستودعات كان يُتابع يدوياً." },
    solution: { en: "IoT-powered WMS with barcode and RFID tracking.", ar: "نظام إدارة مستودعات بتقنية IoT مع تتبع RFID." },
    tech: ["React", "Node.js", "IoT", "PostgreSQL"],
    results: ["99.8% inventory accuracy", "40% faster picking", "Real-time stock updates"],
  },
  {
    slug: "egypt-food-delivery",
    title: { en: "Egypt Food Delivery App", ar: "تطبيق توصيل الطعام في مصر" },
    description: { en: "On-demand food delivery platform connecting restaurants and customers.", ar: "منصة توصيل طعام فوري تربط المطاعم بالعملاء." },
    image: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80",
    category: "E-Commerce",
    client: "Elmenus",
    country: "Egypt",
    problem: { en: "Restaurants had no digital ordering or delivery system.", ar: "المطاعم لم يكن لديها نظام طلبات أو توصيل رقمي." },
    solution: { en: "Full-stack food delivery platform with driver tracking.", ar: "منصة توصيل طعام متكاملة مع تتبع السائقين." },
    tech: ["React Native", "Node.js", "MongoDB", "Google Maps API"],
    results: ["50k daily orders", "3000+ restaurants", "Avg delivery: 28 min"],
  },
  {
    slug: "kuwait-banking-core",
    title: { en: "Kuwait Core Banking System", ar: "نظام البنوك الأساسي في الكويت" },
    description: { en: "Modern core banking system for retail and corporate banking.", ar: "نظام بنكي أساسي حديث للأفراد والشركات." },
    image: "https://images.unsplash.com/photo-1601597111158-2fceff292cdc?w=800&q=80",
    category: "Banking",
    client: "National Bank of Kuwait",
    country: "Kuwait",
    problem: { en: "Legacy core banking system caused delays and errors.", ar: "النظام البنكي القديم كان يسبب تأخيرات وأخطاء." },
    solution: { en: "Cloud-native core banking platform replacing legacy systems.", ar: "نظام بنكي سحابي حديث يحل محل الأنظمة القديمة." },
    tech: ["Java", "Spring Boot", "Oracle", "Kubernetes"],
    results: ["Zero downtime migration", "10x faster transactions", "ISO 27001 certified"],
  },
  {
    slug: "uae-school-management",
    title: { en: "UAE School Management Platform", ar: "منصة إدارة المدارس الإماراتية" },
    description: { en: "Comprehensive school ERP for private schools.", ar: "نظام ERP شامل للمدارس الخاصة." },
    image: "https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=800&q=80",
    category: "Education",
    client: "GEMS Education",
    country: "UAE",
    problem: { en: "Schools managed operations across disconnected tools.", ar: "المدارس كانت تدير عملياتها بأدوات منفصلة." },
    solution: { en: "All-in-one school management ERP with parent portal.", ar: "نظام ERP متكامل لإدارة المدارس مع بوابة للأولياء." },
    tech: ["React", "Laravel", "MySQL", "Firebase"],
    results: ["120+ schools", "50k students", "Parent adoption 85%"],
  },
  {
    slug: "saudi-crm-platform",
    title: { en: "Saudi Enterprise CRM", ar: "نظام إدارة علاقات العملاء السعودي" },
    description: { en: "Custom CRM for managing enterprise sales pipelines.", ar: "نظام CRM مخصص لإدارة مسارات مبيعات الشركات." },
    image: "https://images.unsplash.com/photo-1552664730-d307ca884978?w=800&q=80",
    category: "HR",
    client: "Saudi Telecom Company",
    country: "Saudi Arabia",
    problem: { en: "Sales teams lacked a unified CRM for tracking leads.", ar: "فرق المبيعات كانت تفتقر لنظام موحد لتتبع العملاء." },
    solution: { en: "Custom CRM with AI-powered lead scoring and pipeline.", ar: "نظام CRM مخصص مع تسجيل عملاء محتملين بالذكاء الاصطناعي." },
    tech: ["React", "Node.js", "PostgreSQL", "OpenAI"],
    results: ["35% sales increase", "Unified lead tracking", "AI recommendations"],
  },
  {
    slug: "egypt-logistics-tracking",
    title: { en: "Egypt Last-Mile Delivery", ar: "منصة التوصيل للميل الأخير في مصر" },
    description: { en: "Last-mile delivery tracking for e-commerce.", ar: "تتبع التوصيل للميل الأخير للتجارة الإلكترونية." },
    image: "https://images.unsplash.com/photo-1601584115197-04ecc0da31d7?w=800&q=80",
    category: "Logistics",
    client: "Bosta Egypt",
    country: "Egypt",
    problem: { en: "E-commerce deliveries had poor tracking and delays.", ar: "توصيلات التجارة الإلكترونية كانت تفتقر للتتبع وتتأخر." },
    solution: { en: "Smart last-mile routing and tracking platform.", ar: "منصة ذكية لتحسين مسار التوصيل وتتبعه." },
    tech: ["React Native", "Node.js", "Google Maps API", "AWS"],
    results: ["20% faster delivery", "Real-time SMS tracking", "95% on-time rate"],
  },
  {
    slug: "qatar-real-estate-investment",
    title: { en: "Qatar Real Estate Investment Hub", ar: "منصة الاستثمار العقاري في قطر" },
    description: { en: "Investment platform for commercial real estate in Qatar.", ar: "منصة استثمار عقاري تجاري في قطر." },
    image: "https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800&q=80",
    category: "Real Estate",
    client: "Barwa Real Estate",
    country: "Qatar",
    problem: { en: "Investors had no transparent platform for CRE investments.", ar: "المستثمرون لم يكن لديهم منصة شفافة للاستثمار العقاري." },
    solution: { en: "End-to-end real estate investment and ROI analytics platform.", ar: "منصة متكاملة للاستثمار العقاري وتحليل العائد." },
    tech: ["Next.js", "Python", "PostgreSQL", "Stripe"],
    results: ["$500M transactions", "200+ investors", "Full ROI transparency"],
  },
  {
    slug: "uae-crypto-exchange",
    title: { en: "UAE Crypto Trading Platform", ar: "منصة تداول العملات الرقمية الإماراتية" },
    description: { en: "Regulated cryptocurrency exchange for the UAE market.", ar: "منصة تداول عملات رقمية منظمة للسوق الإماراتي." },
    image: "https://images.unsplash.com/photo-1621761191319-c6fb62004040?w=800&q=80",
    category: "Fintech",
    client: "Hayvn Exchange",
    country: "UAE",
    problem: { en: "UAE investors lacked a locally regulated crypto exchange.", ar: "المستثمرون في الإمارات افتقروا لمنصة تداول رقمي محلية." },
    solution: { en: "Fully licensed crypto exchange with AML compliance.", ar: "منصة تداول مرخصة بالكامل مع امتثال لمكافحة الغسيل." },
    tech: ["React", "Node.js", "PostgreSQL", "WebSocket"],
    results: ["$1B monthly volume", "VASP licensed", "10k active traders"],
  },
  {
    slug: "saudi-fleet-tracking",
    title: { en: "Saudi Smart Fleet Tracking", ar: "نظام تتبع الأسطول الذكي السعودي" },
    description: { en: "GPS-based fleet management for government vehicles.", ar: "نظام إدارة أسطول بالـ GPS للمركبات الحكومية." },
    image: "https://images.unsplash.com/photo-1519003722824-194d4455a60c?w=800&q=80",
    category: "Logistics",
    client: "Saudi National Guard",
    country: "Saudi Arabia",
    problem: { en: "Government fleet had no GPS tracking or reporting.", ar: "الأسطول الحكومي لم يكن له تتبع GPS أو تقارير." },
    solution: { en: "Real-time GPS fleet tracking and driver behavior monitoring.", ar: "تتبع GPS لحظي للأسطول ومراقبة سلوك السائقين." },
    tech: ["React", "IoT", "Node.js", "PostgreSQL"],
    results: ["500+ vehicles tracked", "30% fuel savings", "Driver safety improved"],
  },
  {
    slug: "egypt-hr-payroll",
    title: { en: "Egypt HR & Payroll System", ar: "نظام الرواتب والموارد البشرية في مصر" },
    description: { en: "Localized HR management and payroll system for Egyptian companies.", ar: "نظام موارد بشرية ورواتب موطّن للشركات المصرية." },
    image: "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=800&q=80",
    category: "HR",
    client: "OrascomTech",
    country: "Egypt",
    problem: { en: "Local tax and social insurance rules made payroll complex.", ar: "قواعد الضرائب والتأمين المحلية جعلت الرواتب معقدة." },
    solution: { en: "ETA-compliant payroll and HR platform for Egypt.", ar: "نظام رواتب وموارد بشرية متوافق مع الضرائب المصرية." },
    tech: ["React", "Laravel", "MySQL"],
    results: ["100% tax compliance", "Auto payslips", "ETA e-filing integration"],
  },
  {
    slug: "kuwait-smart-parking",
    title: { en: "Kuwait Smart Parking System", ar: "نظام المواقف الذكية في الكويت" },
    description: { en: "IoT-connected smart parking management for shopping malls.", ar: "إدارة مواقف ذكية بإنترنت الأشياء لمراكز التسوق." },
    image: "https://images.unsplash.com/photo-1506521781263-d8422e82f27a?w=800&q=80",
    category: "Government",
    client: "Avenues Mall Kuwait",
    country: "Kuwait",
    problem: { en: "Parking was chaotic with no real-time availability data.", ar: "كانت المواقف فوضوية بدون بيانات توافر لحظية." },
    solution: { en: "IoT sensor-based smart parking with mobile app guidance.", ar: "نظام مواقف ذكي بمستشعرات IoT مع تطبيق توجيه." },
    tech: ["React Native", "IoT", "Node.js", "MongoDB"],
    results: ["40% less time searching", "90% utilization rate", "Revenue +20%"],
  },
  {
    slug: "uae-digital-health-passport",
    title: { en: "UAE Digital Health Passport", ar: "جواز الصحة الرقمي الإماراتي" },
    description: { en: "Blockchain-backed digital health record and passport platform.", ar: "منصة سجل صحي رقمي مدعوم بالبلوكشين." },
    image: "https://images.unsplash.com/photo-1585435557343-3b092031a831?w=800&q=80",
    category: "Healthcare",
    client: "UAE Ministry of Health",
    country: "UAE",
    problem: { en: "Health records were fragmented across hospitals.", ar: "السجلات الصحية كانت مجزأة بين المستشفيات." },
    solution: { en: "Unified blockchain health record accessible by citizens.", ar: "سجل صحي موحد بالبلوكشين يمكن للمواطنين الوصول إليه." },
    tech: ["React", "Blockchain", "Node.js", "AWS"],
    results: ["3M health records", "Cross-hospital access", "WHO compliant"],
  },
  {
    slug: "saudi-construction-management",
    title: { en: "Saudi Construction Project Management", ar: "منصة إدارة مشاريع البناء السعودية" },
    description: { en: "Digital project management platform for construction companies.", ar: "منصة رقمية لإدارة مشاريع شركات البناء." },
    image: "https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=800&q=80",
    category: "Real Estate",
    client: "Saudi Binladin Group",
    country: "Saudi Arabia",
    problem: { en: "Construction projects lacked centralized tracking and communication.", ar: "مشاريع البناء كانت تفتقر للتتبع والتواصل المركزي." },
    solution: { en: "Construction project management with Gantt, RFI and drawing management.", ar: "إدارة مشاريع بناء مع مخططات جانت وإدارة الرسومات." },
    tech: ["React", "Node.js", "PostgreSQL", "AWS S3"],
    results: ["25% on-time delivery improvement", "50+ active projects", "Zero lost documents"],
  },
  {
    slug: "egypt-social-commerce",
    title: { en: "Egypt Social Commerce App", ar: "تطبيق التجارة الاجتماعية في مصر" },
    description: { en: "Social-first commerce platform for Egyptian creators.", ar: "منصة تجارة اجتماعية لصناع المحتوى المصريين." },
    image: "https://images.unsplash.com/photo-1611926653458-09294b3142bf?w=800&q=80",
    category: "E-Commerce",
    client: "Taager Commerce",
    country: "Egypt",
    problem: { en: "Creators couldn't easily monetize social media audiences.", ar: "صناع المحتوى لم يستطيعوا تحقيق الدخل من جمهورهم بسهولة." },
    solution: { en: "Social commerce platform enabling creator storefronts.", ar: "منصة تجارة اجتماعية لإنشاء متاجر لصناع المحتوى." },
    tech: ["React Native", "Node.js", "MongoDB", "Stripe"],
    results: ["30k creators", "2M products sold", "Creator earnings +300%"],
  },
  {
    slug: "qatar-port-management",
    title: { en: "Qatar Port Management System", ar: "نظام إدارة الموانئ القطري" },
    description: { en: "Digital operations platform for Qatar's major seaports.", ar: "منصة عمليات رقمية لموانئ قطر الكبرى." },
    image: "https://images.unsplash.com/photo-1567449303078-57ad995bd17f?w=800&q=80",
    category: "Logistics",
    client: "Mwani Qatar",
    country: "Qatar",
    problem: { en: "Port operations were paper-based and error-prone.", ar: "عمليات الميناء كانت ورقية وعرضة للأخطاء." },
    solution: { en: "End-to-end digital port operations and cargo tracking platform.", ar: "منصة رقمية متكاملة لعمليات الميناء وتتبع البضائع." },
    tech: ["React", "Java", "Oracle", "AWS"],
    results: ["60% faster customs clearance", "Full cargo visibility", "Paperless ops"],
  },
  {
    slug: "uae-energy-management",
    title: { en: "UAE Smart Energy Platform", ar: "منصة إدارة الطاقة الذكية الإماراتية" },
    description: { en: "Smart energy monitoring and management for commercial buildings.", ar: "مراقبة وإدارة طاقة ذكية للمباني التجارية." },
    image: "https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=800&q=80",
    category: "Government",
    client: "DEWA Smart Grid",
    country: "UAE",
    problem: { en: "Buildings had no granular energy consumption visibility.", ar: "المباني لم يكن لها رؤية تفصيلية لاستهلاك الطاقة." },
    solution: { en: "IoT energy monitoring with automated optimization and alerts.", ar: "مراقبة طاقة بإنترنت الأشياء مع تحسين آلي وتنبيهات." },
    tech: ["React", "IoT", "Python", "InfluxDB"],
    results: ["20% energy reduction", "Real-time dashboards", "CO2 tracking"],
  },
  {
    slug: "saudi-recruitment-platform",
    title: { en: "Saudi Recruitment Platform", ar: "منصة التوظيف السعودية" },
    description: { en: "AI-powered job matching and recruitment platform.", ar: "منصة توظيف وتوافق وظيفي بالذكاء الاصطناعي." },
    image: "https://images.unsplash.com/photo-1521737711867-e3b97375f902?w=800&q=80",
    category: "HR",
    client: "Bayt.com Saudi",
    country: "Saudi Arabia",
    problem: { en: "Recruiters spent hours manually screening candidates.", ar: "المتعهدون كانوا يقضون ساعات في فرز المرشحين." },
    solution: { en: "AI-driven recruitment platform with ATS and video interviews.", ar: "منصة توظيف بالذكاء الاصطناعي مع ATS ومقابلات فيديو." },
    tech: ["React", "Python", "OpenAI", "PostgreSQL"],
    results: ["80% less screening time", "10k job listings", "AI match accuracy 90%"],
  },
  {
    slug: "egypt-inventory-management",
    title: { en: "Egypt Retail Inventory System", ar: "نظام إدارة مخزون التجزئة في مصر" },
    description: { en: "Centralized inventory management for retail chains.", ar: "نظام مركزي لإدارة مخزون سلاسل التجزئة." },
    image: "https://images.unsplash.com/photo-1553413077-190dd305871c?w=800&q=80",
    category: "Retail",
    client: "Carrefour Egypt",
    country: "Egypt",
    problem: { en: "Stock discrepancies led to overstocking and shortages.", ar: "تفاوتات المخزون أدت لتخزين زائد ونقص في السلع." },
    solution: { en: "Real-time inventory tracking with reorder automation.", ar: "تتبع مخزون لحظي مع أتمتة إعادة الطلب." },
    tech: ["React", "Node.js", "PostgreSQL", "Redis"],
    results: ["99% stock accuracy", "Automated reorders", "Shrinkage -30%"],
  },
  {
    slug: "kuwait-digital-government",
    title: { en: "Kuwait Digital Government Hub", ar: "مركز الحكومة الرقمية في الكويت" },
    description: { en: "Centralized platform for all government digital services.", ar: "منصة مركزية لجميع الخدمات الحكومية الرقمية." },
    image: "https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=800&q=80",
    category: "Government",
    client: "Kuwait CITRA",
    country: "Kuwait",
    problem: { en: "Citizens navigated 30+ separate government websites.", ar: "المواطنون كانوا يتنقلون بين أكثر من 30 موقع حكومي." },
    solution: { en: "Unified citizen portal aggregating all government services.", ar: "بوابة موحدة تجمع جميع الخدمات الحكومية." },
    tech: ["Next.js", "Java", "Oracle", "Redis"],
    results: ["4M citizens", "60+ services", "70% online adoption"],
  },
  {
    slug: "uae-hotel-management",
    title: { en: "UAE Luxury Hotel Management", ar: "نظام إدارة الفنادق الفاخرة الإماراتية" },
    description: { en: "Property management system for 5-star hotel chains.", ar: "نظام إدارة عقارات لسلاسل فنادق 5 نجوم." },
    image: "https://images.unsplash.com/photo-1542314831-068cd1dbfeeb?w=800&q=80",
    category: "Tourism",
    client: "Jumeirah Group",
    country: "UAE",
    problem: { en: "Front desk and operations were managed across siloed tools.", ar: "الاستقبال والعمليات كانا يُداران بأدوات منفصلة." },
    solution: { en: "Integrated hotel PMS with booking, housekeeping and F&B.", ar: "نظام إدارة فندق متكامل مع الحجوزات والتدبير والمطعم." },
    tech: ["React", "Node.js", "PostgreSQL", "Stripe"],
    results: ["50+ hotels", "RevPAR +15%", "Guest satisfaction 98%"],
  },
  {
    slug: "saudi-media-streaming",
    title: { en: "Saudi Media Streaming Platform", ar: "منصة البث الإعلامي السعودية" },
    description: { en: "Arabic-first video streaming platform for MENA audiences.", ar: "منصة بث فيديو عربية أولاً لجمهور منطقة الشرق الأوسط." },
    image: "https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=800&q=80",
    category: "E-Commerce",
    client: "STC TV",
    country: "Saudi Arabia",
    problem: { en: "MENA lacked a dedicated Arabic-first streaming platform.", ar: "المنطقة كانت تفتقر لمنصة بث عربية مخصصة." },
    solution: { en: "Full-featured streaming platform with CDN and Arabic subtitles.", ar: "منصة بث متكاملة مع CDN وترجمة عربية." },
    tech: ["React", "Node.js", "AWS CloudFront", "FFmpeg"],
    results: ["5M subscribers", "HDR streaming", "Arabic subtitle AI"],
  },
  {
    slug: "egypt-smart-agriculture",
    title: { en: "Egypt Smart Agriculture Platform", ar: "منصة الزراعة الذكية في مصر" },
    description: { en: "IoT-based precision agriculture platform for Egyptian farms.", ar: "منصة زراعة دقيقة بإنترنت الأشياء للمزارع المصرية." },
    image: "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800&q=80",
    category: "Government",
    client: "Ministry of Agriculture Egypt",
    country: "Egypt",
    problem: { en: "Farmers lacked data-driven irrigation and crop management.", ar: "المزارعون افتقروا لإدارة الري والمحاصيل بالبيانات." },
    solution: { en: "Smart IoT sensors with AI-based crop monitoring and alerts.", ar: "مستشعرات IoT ذكية مع مراقبة محاصيل بالذكاء الاصطناعي." },
    tech: ["React", "IoT", "Python", "InfluxDB"],
    results: ["30% water savings", "15% yield increase", "10k farms connected"],
  },
  {
    slug: "qatar-cybersecurity-platform",
    title: { en: "Qatar National Cybersecurity Platform", ar: "منصة الأمن السيبراني الوطنية القطرية" },
    description: { en: "National cybersecurity monitoring and incident response platform.", ar: "منصة وطنية لمراقبة الأمن السيبراني والاستجابة للحوادث." },
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=800&q=80",
    category: "Government",
    client: "Qatar NCSC",
    country: "Qatar",
    problem: { en: "Cyber threats had no centralized monitoring or response system.", ar: "التهديدات السيبرانية لم يكن لها نظام مراقبة واستجابة مركزي." },
    solution: { en: "SIEM-based national cybersecurity operations center platform.", ar: "منصة مركز عمليات أمن سيبراني وطني مبنية على SIEM." },
    tech: ["React", "Python", "Elasticsearch", "Kafka"],
    results: ["1M+ threats detected", "MTTR reduced 60%", "ISO 27001 compliant"],
  },
  {
    slug: "uae-wealthtech-platform",
    title: { en: "UAE Wealth Management Platform", ar: "منصة إدارة الثروات الإماراتية" },
    description: { en: "Digital wealth management and robo-advisory platform.", ar: "منصة رقمية لإدارة الثروات والاستشارة الآلية." },
    image: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=800&q=80",
    category: "Fintech",
    client: "ADCB Securities",
    country: "UAE",
    problem: { en: "High-net-worth clients lacked digital wealth management tools.", ar: "العملاء ذوو الثروات الكبيرة افتقروا لأدوات رقمية لإدارة الثروات." },
    solution: { en: "Robo-advisory platform with portfolio automation and reporting.", ar: "منصة استشارة آلية مع أتمتة المحافظ والتقارير." },
    tech: ["React", "Python", "PostgreSQL", "AWS"],
    results: ["$2B AUM", "Avg return +12%", "Full regulatory compliance"],
  },
  {
    slug: "saudi-events-platform",
    title: { en: "Saudi Events Management Platform", ar: "منصة إدارة الفعاليات السعودية" },
    description: { en: "End-to-end event management and ticketing platform.", ar: "منصة متكاملة لإدارة الفعاليات والتذاكر." },
    image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=800&q=80",
    category: "E-Commerce",
    client: "Riyadh Season",
    country: "Saudi Arabia",
    problem: { en: "Large events had no integrated ticketing and management system.", ar: "الفعاليات الكبيرة لم يكن لها نظام متكامل للتذاكر والإدارة." },
    solution: { en: "Scalable event platform handling millions of concurrent tickets.", ar: "منصة فعاليات قابلة للتوسع تتعامل مع ملايين التذاكر المتزامنة." },
    tech: ["Next.js", "Node.js", "Redis", "AWS"],
    results: ["5M tickets sold", "Zero downtime events", "NFC entry gates"],
  },
  {
    slug: "egypt-digital-banking",
    title: { en: "Egypt Neobank Platform", ar: "منصة البنك الرقمي في مصر" },
    description: { en: "Fully digital neo-banking experience for Egyptian consumers.", ar: "تجربة بنكية رقمية كاملة للمستهلكين المصريين." },
    image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=800&q=80",
    category: "Banking",
    client: "Telda Egypt",
    country: "Egypt",
    problem: { en: "Millions of Egyptians were unbanked or underbanked.", ar: "ملايين المصريين كانوا خارج المنظومة المصرفية." },
    solution: { en: "Mobile-first neobank with instant account opening and transfers.", ar: "بنك رقمي mobile-first مع فتح حساب فوري وتحويلات." },
    tech: ["Flutter", "Node.js", "PostgreSQL", "AWS"],
    results: ["1M accounts opened", "Instant KYC", "CBE licensed"],
  },
  {
    slug: "kuwait-telematics",
    title: { en: "Kuwait Fleet Telematics", ar: "نظام تيليماتكس للأسطول في الكويت" },
    description: { en: "Telematics and driver safety platform for commercial fleets.", ar: "نظام تيليماتكس وسلامة السائقين للأساطيل التجارية." },
    image: "https://images.unsplash.com/photo-1449965408869-eaa3f722e40d?w=800&q=80",
    category: "Logistics",
    client: "Agility Kuwait",
    country: "Kuwait",
    problem: { en: "Fleet operators had no driver behavior monitoring.", ar: "مشغلو الأسطول لم يكن لديهم مراقبة لسلوك السائقين." },
    solution: { en: "Telematics platform with driver scoring and live dashcam feeds.", ar: "منصة تيليماتكس مع تسجيل نقاط السائقين وكاميرات حية." },
    tech: ["React", "IoT", "Node.js", "PostgreSQL"],
    results: ["40% accident reduction", "Live driver feeds", "Insurance savings 20%"],
  },
  {
    slug: "uae-proptech-mortgage",
    title: { en: "UAE PropTech Mortgage Platform", ar: "منصة قروض العقارات الإماراتية" },
    description: { en: "Digital mortgage origination and management platform.", ar: "منصة رقمية لإنشاء وإدارة قروض العقارات." },
    image: "https://images.unsplash.com/photo-1560520031-3a4dc4e9de0c?w=800&q=80",
    category: "Fintech",
    client: "HSBC UAE",
    country: "UAE",
    problem: { en: "Mortgage applications took 6 weeks with manual paper processes.", ar: "طلبات القروض كانت تستغرق 6 أسابيع بعمليات ورقية." },
    solution: { en: "End-to-end digital mortgage platform with instant pre-approval.", ar: "منصة قروض رقمية متكاملة مع موافقة مبدئية فورية." },
    tech: ["React", "Node.js", "PostgreSQL", "DocuSign API"],
    results: ["Application time: 6 weeks → 48 hours", "100% digital", "UAE Central Bank approved"],
  },
  {
    slug: "saudi-water-utility",
    title: { en: "Saudi Water Utility Platform", ar: "منصة إدارة المياه السعودية" },
    description: { en: "Smart water network monitoring and management platform.", ar: "منصة ذكية لمراقبة وإدارة شبكة المياه." },
    image: "https://images.unsplash.com/photo-1548438294-1ad5d5f4f063?w=800&q=80",
    category: "Government",
    client: "NWC Saudi Arabia",
    country: "Saudi Arabia",
    problem: { en: "Water leaks and losses had no detection or prevention system.", ar: "تسربات المياه لم يكن لها نظام كشف أو منع." },
    solution: { en: "IoT water network monitoring with AI-based leak detection.", ar: "مراقبة شبكة مياه بإنترنت الأشياء مع كشف تسرب بالذكاء الاصطناعي." },
    tech: ["React", "IoT", "Python", "InfluxDB"],
    results: ["25% water loss reduction", "Real-time leak alerts", "10k sensors deployed"],
  },
  {
    slug: "egypt-ride-hailing",
    title: { en: "Egypt Ride-Hailing Platform", ar: "منصة استدعاء سيارات الأجرة في مصر" },
    description: { en: "On-demand ride-hailing and mobility platform.", ar: "منصة استدعاء سيارات وتنقل حسب الطلب." },
    image: "https://images.unsplash.com/photo-1549317661-bd32c8ce0db2?w=800&q=80",
    category: "Mobile",
    client: "InDrive Egypt",
    country: "Egypt",
    problem: { en: "Drivers and riders lacked a fair, local mobility platform.", ar: "السائقون والركاب افتقروا لمنصة تنقل محلية عادلة." },
    solution: { en: "Ride-hailing app with price negotiation and driver ratings.", ar: "تطبيق استدعاء سيارات مع تفاوض على السعر وتقييم السائقين." },
    tech: ["Flutter", "Node.js", "MongoDB", "Google Maps API"],
    results: ["2M rides/month", "50k drivers", "Avg rating 4.7"],
  },
  {
    slug: "qatar-loyalty-platform",
    title: { en: "Qatar Retail Loyalty Platform", ar: "منصة ولاء التجزئة القطرية" },
    description: { en: "Multi-brand customer loyalty and rewards platform.", ar: "منصة ولاء ومكافآت متعددة العلامات التجارية." },
    image: "https://images.unsplash.com/photo-1607082349566-187342175e2f?w=800&q=80",
    category: "Retail",
    client: "Doha Festival City",
    country: "Qatar",
    problem: { en: "Retailers lacked a unified loyalty program.", ar: "تجار التجزئة افتقروا لبرنامج ولاء موحد." },
    solution: { en: "Unified loyalty platform with digital wallet and gamification.", ar: "منصة ولاء موحدة مع محفظة رقمية وألعاب تفاعلية." },
    tech: ["React Native", "Node.js", "PostgreSQL", "Redis"],
    results: ["500k members", "40% repeat visits", "Points redemption 85%"],
  },
  {
    slug: "uae-legal-tech",
    title: { en: "UAE Legal Document Automation", ar: "أتمتة الوثائق القانونية الإماراتية" },
    description: { en: "AI-powered legal document drafting and management platform.", ar: "منصة صياغة وإدارة وثائق قانونية بالذكاء الاصطناعي." },
    image: "https://images.unsplash.com/photo-1589216532372-1c2a367900d9?w=800&q=80",
    category: "Fintech",
    client: "Al Tamimi & Co",
    country: "UAE",
    problem: { en: "Legal drafting was slow, expensive and error-prone.", ar: "صياغة العقود كانت بطيئة ومكلفة وعرضة للأخطاء." },
    solution: { en: "AI legal document automation with clause library and e-signatures.", ar: "أتمتة وثائق قانونية بالذكاء الاصطناعي مع مكتبة بنود وتوقيع إلكتروني." },
    tech: ["React", "Python", "OpenAI", "PostgreSQL"],
    results: ["80% faster drafting", "50k documents generated", "99% accuracy rate"],
  },
  {
    slug: "saudi-pharma-supply",
    title: { en: "Saudi Pharma Supply Chain", ar: "سلسلة توريد الأدوية السعودية" },
    description: { en: "End-to-end pharmaceutical supply chain and cold chain platform.", ar: "منصة متكاملة لسلسلة توريد الأدوية والسلسلة الباردة." },
    image: "https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=800&q=80",
    category: "Healthcare",
    client: "IQVIA Saudi Arabia",
    country: "Saudi Arabia",
    problem: { en: "Cold-chain pharma shipments had no temperature monitoring.", ar: "شحنات الأدوية في السلسلة الباردة لم يكن لها مراقبة حرارة." },
    solution: { en: "IoT cold-chain monitoring with real-time temperature alerts.", ar: "مراقبة سلسلة باردة بإنترنت الأشياء مع تنبيهات حرارية لحظية." },
    tech: ["React", "IoT", "Node.js", "InfluxDB"],
    results: ["Zero spoilage incidents", "SFDA compliant", "500+ shipments tracked"],
  },
  {
    slug: "egypt-microfinance-platform",
    title: { en: "Egypt Microfinance Platform", ar: "منصة التمويل الصغير في مصر" },
    description: { en: "Digital microfinance and lending platform for SMEs.", ar: "منصة تمويل صغير ورقمي للشركات الصغيرة والمتوسطة." },
    image: "https://images.unsplash.com/photo-1579621970563-ebec7560ff3e?w=800&q=80",
    category: "Fintech",
    client: "Tanmeyah Microfinance",
    country: "Egypt",
    problem: { en: "SMEs struggled to access formal financing channels.", ar: "الشركات الصغيرة كانت تجد صعوبة في الحصول على تمويل رسمي." },
    solution: { en: "Digital loan origination with AI credit scoring for SMEs.", ar: "إنشاء قروض رقمي مع تسجيل ائتماني بالذكاء الاصطناعي." },
    tech: ["React", "Python", "PostgreSQL", "AWS"],
    results: ["50k loans disbursed", "Default rate < 2%", "FRA licensed"],
  },
  {
    slug: "kuwait-customs-platform",
    title: { en: "Kuwait Digital Customs Platform", ar: "منصة الجمارك الرقمية الكويتية" },
    description: { en: "Digital customs declaration and clearance platform.", ar: "منصة رقمية للإقرار الجمركي والتخليص." },
    image: "https://images.unsplash.com/photo-1578575437130-527eed3abbec?w=800&q=80",
    category: "Government",
    client: "Kuwait General Customs",
    country: "Kuwait",
    problem: { en: "Customs clearance required physical paperwork and took days.", ar: "التخليص الجمركي كان يتطلب أوراقاً ورقية ويستغرق أياماً." },
    solution: { en: "Paperless digital customs portal with AI document verification.", ar: "بوابة جمارك رقمية بلا ورق مع التحقق الآلي من الوثائق." },
    tech: ["Next.js", "Python", "Oracle", "AWS"],
    results: ["Clearance: 3 days → 4 hours", "100% digital", "WCO compliant"],
  },
  {
    slug: "uae-fitness-app",
    title: { en: "UAE Fitness & Wellness App", ar: "تطبيق اللياقة والصحة الإماراتي" },
    description: { en: "AI-powered fitness and wellness coaching platform.", ar: "منصة تدريب لياقة وصحة بالذكاء الاصطناعي." },
    image: "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=800&q=80",
    category: "Healthcare",
    client: "Technogym UAE",
    country: "UAE",
    problem: { en: "Fitness centers lacked digital engagement tools for members.", ar: "مراكز اللياقة كانت تفتقر لأدوات تفاعل رقمي مع الأعضاء." },
    solution: { en: "AI fitness app with personalized plans, live classes and nutrition.", ar: "تطبيق لياقة ذكي مع خطط شخصية وفصول مباشرة وتغذية." },
    tech: ["Flutter", "Node.js", "MongoDB", "OpenAI"],
    results: ["200k users", "70% retention rate", "Avg 4 workouts/week"],
  },
  {
    slug: "saudi-hajj-management",
    title: { en: "Saudi Hajj Pilgrim Platform", ar: "منصة إدارة الحج السعودية" },
    description: { en: "Digital pilgrim management and safety tracking for Hajj season.", ar: "إدارة رقمية للحجاج وتتبع سلامتهم في موسم الحج." },
    image: "https://images.unsplash.com/photo-1591604466107-ec97de577aff?w=800&q=80",
    category: "Government",
    client: "Saudi Ministry of Hajj",
    country: "Saudi Arabia",
    problem: { en: "Managing 2M pilgrims safely with no digital system was a huge challenge.", ar: "إدارة 2 مليون حاج بدون نظام رقمي كانت تحدياً ضخماً." },
    solution: { en: "Pilgrim digital ID, crowd management and emergency response platform.", ar: "هوية رقمية للحجاج وإدارة حشود ومنصة استجابة طوارئ." },
    tech: ["React Native", "IoT", "Node.js", "AWS"],
    results: ["2M pilgrims tracked", "Real-time crowd safety", "Zero incidents 3 years"],
  },
  {
    slug: "egypt-solar-energy",
    title: { en: "Egypt Solar Energy Management", ar: "منصة إدارة الطاقة الشمسية في مصر" },
    description: { en: "Solar farm monitoring and energy trading platform.", ar: "منصة مراقبة مزارع الطاقة الشمسية وتداول الطاقة." },
    image: "https://images.unsplash.com/photo-1508514177221-188b1cf16e9d?w=800&q=80",
    category: "Government",
    client: "Benban Solar Park",
    country: "Egypt",
    problem: { en: "Solar operators had no unified monitoring for farm performance.", ar: "مشغلو الطاقة الشمسية لم يكن لديهم مراقبة موحدة للأداء." },
    solution: { en: "Real-time solar farm monitoring with predictive maintenance.", ar: "مراقبة لحظية لمزارع الطاقة الشمسية مع صيانة تنبؤية." },
    tech: ["React", "IoT", "Python", "InfluxDB"],
    results: ["200 MW monitored", "Uptime 99.5%", "15% efficiency gain"],
  },
];